name: Deploy Infrastructure
on:
  push:
    branches: [ "master" ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-north-1"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="db_password="db_password=your_secure_password" \
            -var='subnet_ids=["subnet-123456","subnet-789012"]' \
            -input=false \
            -out=tfplan
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Terraform Apply
        run: |
          terraform plan \
            -var="db_password="db_password=your_secure_password" \
            -var='subnet_ids=["subnet-123456","subnet-789012"]' \
            -input=false \
            tfplan
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Store Outputs in SSM
        run: |
          cd ./terraform
          # Get raw outputs without quotes
          RDS_ENDPOINT=$(terraform output rds_endpoint | grep -oE '".*"' | tr -d '"' | head -1)
          RDS_USERNAME=$(terraform output rds_username | grep -oE '".*"' | tr -d '"' | head -1)

          echo "Stored S3 Bucket: $RDS_ENDPOINT"
          echo "Stored CloudFront ID: $RDS_ENDPOINT"
          aws ssm put-parameter --name "/app/rds_endpoint" --value "$RDS_ENDPOINT" --type String --overwrite
          aws ssm put-parameter --name "/app/rds_username" --value "$RDS_USERNAME" --type String --overwrite